# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workboard',
            old_name='hit',
            new_name='hits',
        ),
    ]
