# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170516_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=1000)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(max_length=99999999)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('public_yn', models.CharField(max_length=1)),
                ('start_dt', models.CharField(max_length=14)),
                ('end_dt', models.CharField(max_length=14)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip_master',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='trip_master',
            name='trip_day',
        ),
        migrations.RemoveField(
            model_name='trip_day',
            name='Trip_schedule',
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip_day',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip_schedule',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Trip_master',
        ),
    ]
