# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170516_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_master',
            name='trip_no',
        ),
    ]
